### ISSUE TITLE
Suggestion: Pre-populate s:digraphs

### ISSUE THREAD

**Issue by Asheq** [tpope/vim-characterize#13]
`chracterize#digraphs` takes a little long to run the first time (almost a tenth of a second). Pressing `ga` for the first time causes a little bit of a screen flash because of this.

This seems to be because `s:digraphs` is generated dynamically the first time `ga` is invoked. Might I suggest `s:digraphs` be pre-populated like the other objects (like `s:d` and `s:html_entities`)?

@tpope If you agree, I can submit a PR for this.

**Comment by tpope** [comment]
Digraphs vary from version to version of Vim, plus users can define their own. I don't think we can hard code them.

**Comment by Asheq** [comment]
Ahh, I didn't realize. That's fair enough. Do you see any way to reduce the flicker/flash of the screen on the first `ga`? I don't want to bother you with such a minor issue, but just checking in case there is something easy you could spot quickly.

**Comment by tpope** [comment]
Nothing obvious no. You could maybe skip the load for plain ASCII characters if that's a common use case for you.

**Comment by Asheq** [comment]
Alright, thanks for looking into it!
