### ISSUE TITLE
Provide `:Ascii` user command

### ISSUE THREAD

**Issue by MithicSpirit** [tpope/vim-characterize#22]
Regular `ga` is also available through `:ascii`, so it would make sense for this to provide something similar for people that have `ga` mapped to something else. `:Ascii` feels like the most natural user command for this.

**Comment by tpope** [comment]
Capitalizing a built-in is an approach I am quite fond of, but in this case, the name of the plugin works perfectly, so I am using that instead. This also gives us a nice way to act on an argument.
