### ISSUE TITLE
uconv for querying

### ISSUE THREAD

**Issue by avidseeker** [tpope/vim-characterize#24]
Having 37806 lines of code just for a simple Vim plugin is probably not good.

Consider using `uconv`  for querying Unicode names. [icu](https://icu.unicode.org) comes as  a core package in almost all systems.

```sh
$ echo μ | uconv -f utf-8 -x any-name
\N{GREEK SMALL LETTER MU}\N{<control-000A>}%
```

**Comment by tpope** [comment]
I'm not seeing `uconv` anywhere on macOS. And I'm guessing it's not on Windows? Size aside, it would be nice if I wasn't responsible for keeping the list up-to-date, but without those 2 platforms it's sadly a non-starter.
