### ISSUE TITLE
<script> map makes mapping outside script impossible?

### ISSUE THREAD

**Issue by Konfekt** [tpope/vim-characterize#7]
Since 
```
nnoremap <silent><script> <Plug>(characterize) :<C-U>echo <SID>info(matchstr(getline('.')[col('.')-1:-1],'.'))<CR>
```
is a scipt map, how to map it outside of characterize.vim?

**Comment by tpope** [comment]
Same as any other map.

    nmap abc123 <Plug>(characterize)

**Comment by Konfekt** [comment]
? Over here (Linux, Vim 7.4.580) it has no effect if `nmap abc123 <Plug>(characterize)` is outside of `characterize.vim`.

**Comment by Konfekt** [comment]
Ah, the culprit is:
```
Note: ":map <script>" and ":noremap <script>" do the same thing. 
``
Therefore the mapping does not work if the user has remapped any of the characters in
```
:<C-U>echo <SID>info(matchstr(getline('.')[col('.')-1:-1],'.'))<CR>
```

Since you write `nnoremap` perhaps you mean `nnoremap` ?

**Comment by tpope** [comment]
I wouldn't expect any of that to cause a discrepancy between creating a map inside and outside the plugin. I'm on 7.4.273, and I guess it could possibly be a bug in your Vim version.

I don't understand your question.

**Comment by Konfekt** [comment]
Yeah, it should work but does not. Remapping onky should take place script locally. Could you try remapping : and mapping (plug)characterize outside of characterize.vim to check if this works as expected?

**Comment by tpope** [comment]
Yes, it works fine.

**Comment by Konfekt** [comment]
Ok, then it's a vim bug.

**Comment by Konfekt** [comment]
It works fine out of the box though, if mapped to ga.
