### ISSUE TITLE
Upgrade to Unicode 8.0

### ISSUE THREAD

**Issue by glts** [tpope/vim-characterize#8]
Quite a few codepoints have been added in the last two years. An upgrade would be much appreciated.

**Comment by tpope** [comment]
Sure would!

**Comment by glts** [comment]
Great! Do you still have the script handy that you used to generate the dict, or do you accept a pull request? (I imagine it's going to be a large diff. I can't promise anything.)

**Comment by tpope** [comment]
IIRC all I did was paste the full list into a text file and use `<C-V>` block editing to beat it into shape.

**Comment by tpope** [comment]
I don't remember where I got the list.

**Comment by glts** [comment]
Probs this one http://www.unicode.org/Public/UCD/latest/ucd/UnicodeData.txt.

**Comment by justinmk** [comment]
http://www.unicode.org/Public/UNIDATA/UnicodeData.txt is what Vim/Neovim use. [This lua script](https://github.com/neovim/neovim/blob/master/scripts/genunicodetables.lua) parses that file and builds a lua table, it could be a good starting point.
