### ISSUE TITLE
the cursor moves one character (...) when 'normal ga' returns NUL

### ISSUE THREAD

**Issue by sharethewisdom** [tpope/vim-characterize#9]
I have

``` vim
set cmdheight=2
augroup AutoSeeCharInfo
  au!
  au CursorHoldI * normal ga
augroup END
```

in my neovim configs. Obviously, while entering text, the cursor is often just before the newline, causing the normal command to return NUL and shift the cursor to the previous character. This is probably not considered a bug. Could someone please help me understand how to do this correctly?

I can do without this auto command. But still, it's useful to learn character names while working, and thanks to the timeout, performance isn't noticeably affected.

**Comment by TheDerkus** [comment]
This behavior does not occur when 'virtualedit' is set to 'onemore' or 'all'. I tried creating a small wrapper that would set 'virtualedit', execute the `ga` command, and then reset 'virtualedit', but haven't been able to make it work.

**Comment by TheDerkus** [comment]
I managed to make it work with a different approach:

    autocmd CursorHoldI * if col('.') < col('$') | execute "normal ga" | endif

**Comment by alerque** [comment]
I've never seen this. I'm a full time Neovim user and use have used this plugin since March 2016. I do not have anything set for `virtualedit`. This is either already fixed (it is possible this was done early in 2016 and I missed it) or it does not affect all systems (a bad interaction with some _other_ setting?).

**Comment by tpope** [comment]
Rereading, I think this is entirely an artifact of the autocommand, and since a different autocommand works, I think this can indeed be closed.

**Comment by sharethewisdom** [comment]
ok.

(It's not an issue for me anymore, but I couldn't exactly trace the settings, like virtualedit, I used at the time)

**Comment by tpope** [comment]
It's an issue with the default settings. It's also an issue if characterize isn't installed, or you use `normal! ga` to invoke the built-in. `CursorHoldI` just wasn't built for these kinds of shenanigans.
